version: '3.8'
services:
    memcached:
        image: 'memcached:alpine'

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '30002:8025'

    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=db
        ports:
            - '30005:5432'

    elasticsearch:
        image: 'elasticsearch:6.5.4'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './sconmag:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '30001:80'

    php-fpm:
        build:
            context: phpdocker/php-fpm
            args:
                WWWUSER: '${UID}'
        working_dir: /application
        volumes:
            - './sconmag:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
